### ISSUE TITLE
How does pytetgen generate region markers?

### ISSUE THREAD

**Issue by stefsmeets** [hpgem/nanomesh#109]
Test how `pytetgen` works with region markers.

- [ ] If we use default region markers (just `-A`), can we use `pytetgen` for that?
- [ ] How does `pytetgen` handle region markers?

Follow-up from #108

**Comment by stefsmeets** [comment]
Region attributes are not supported by `pytetgen`.

Open issue on `pytetgen` requesting support for region attributes: https://github.com/pyvista/tetgen/issues/22

**Comment by stefsmeets** [comment]
This is no longer needed with the current system in place. If `pytetgen` ever gets support for regions, this can be re-opened.

**Comment by akaszynski** [comment]
> This is no longer needed with the current system in place. If pytetgen ever gets support for regions, this can be re-opened.

Supports it now.
