### ISSUE TITLE
Moving points in ROI-selection sometimes clones them

### ISSUE THREAD

**Issue by Laar** [hpgem/nanomesh#130]
My process for selecting a ROI of an image is at the moment to make a rough selection, and then start dragging the corner points. This is done by dragging the point while holding ctrl. 

However, for some vertices doing a ctrl-drag instead introduces a new vertex that is then dragged around. The patterns that I have found so far are:
 1. Usually the start/end vertex has this property (maybe because it is clicked on twice?)
 2. Some of the vertices may look darker, they often seem to have this property, the starting vertex usually has this property.

This duplication means that such a point becomes really hard to move, as most of the times it gets duplicated instead of moved. A result of attempting to move the point (and finally succeed) is shown below. Note that three vertices are a darker blacker than the others. When moving these vertices they get duplicated (condition 2).

![duplication](https://user-images.githubusercontent.com/731831/138094822-6262b6b9-dd89-4e5c-9d13-63fb39564c1f.png)

**Comment by stefsmeets** [comment]
True, then it is easier to start over (<escape> resets the points), because when dragging the points don't snap.
