### ISSUE TITLE
Export zones to gmsh in standard format

### ISSUE THREAD

**Issue by Laar** [hpgem/nanomesh#135]
Currently nanomesh exports the regions/zones to gmsh using integers, in what is best described as a custom format. It looks like that gmsh has a way to export this information in the physicalnames section, and then setting the right tag on each element.

It would be nice to support this way of importing/exporting the region information, as it has several benefits:
 1. It can use names instead of numbers, making it much easier to remember which region is what part of the mesh.
 2. Meshes can be read in by gmsh based tools and then exported without loss of information. For example to refine the mesh.
 3. nanomesh can then read files generated by gmsh and use them for processing.

Note with regards to point 2, it can currently read the data, but shows it as a solution value, not as a region.

**Comment by stefsmeets** [comment]
Hi @laar, thanks for the suggestion. This is on my personal wishlist as well. I have used integers as they are easy to increment, but I don't see any reason why it wouldn't work with names. I will have a look and see what I can do 👍

**Comment by stefsmeets** [comment]
> Note with regards to point 2, it can currently read the data, but shows it as a solution value, not as a region.

Is this an issue by itself?

**Comment by Laar** [comment]
> > Note with regards to point 2, it can currently read the data, but shows it as a solution value, not as a region.
> 
> Is this an issue by itself?

It is more a consequence of the current way we export the information. We write it to a 'section' (for lack of better word) of the file that gmsh interprets as solutions. So if we can move the data to the intended section, then we automatically get rid of this. If not, then it is just the a consequence of the way we do it.

**Comment by Laar** [comment]
> Hi @Laar, thanks for the suggestion. This is on my personal wishlist as well. I have used integers as they are easy to increment, but I don't see any reason why it wouldn't work with names. I will have a look and see what I can do +1

I can see if I can make a mesh file with multiple regions in gmsh. Then you can see where they end up after importing.

**Comment by Laar** [comment]
I've created a mesh with gmsh with multiple regions which have a name. It also should have some edges that are labeled. Might be useful for this to compare.

[ReferenceMesh-coarse.msh.zip](https://github.com/hpgem/nanomesh/files/7541150/ReferenceMesh-coarse.msh.zip)

![Screenshot_2021-11-15_20-17-01](https://user-images.githubusercontent.com/731831/141840889-f41316f9-e565-460d-8de3-3c13d17479e3.png)

**Comment by stefsmeets** [comment]
Thanks @laar, I was just starting to work on this yesterday, so your timing could not be better 😁

I think I got the data format figured out, just need to think a bit how to make it all fit together:

![image](https://user-images.githubusercontent.com/873520/141975767-9078e15f-fafb-4e55-97df-cafe7b2843cc.png)

**Comment by Laar** [comment]
Looks very nice. It seems that the back interface labeling is lost in mesh my own mesh generation. So something to fix on my side.

**Comment by stefsmeets** [comment]
Hi @laar, could you have a look at the mesh I generated whether that fits with what you had in mind? And if they work with gmsh?

For the zones, I just have the internal/external boundaries for now. We can talk about which zones/names would be useful later :-)

[out.zip](https://github.com/hpgem/nanomesh/files/7587422/out.zip)

**Comment by Laar** [comment]
@stefsmeets That looks very nice, still have to add the reading code to hpgem. Looking at the gmsh output by eye it seems to be what I expected.

**Comment by stefsmeets** [comment]
Thanks @laar for checking, in that case I will close this issue. If you run into any issues, then please let me know :)
