### ISSUE TITLE
Look into labeling some sets of faces

### ISSUE THREAD

**Issue by Laar** [hpgem/nanomesh#136]
Currently only the elements get a label, which is then used to assign material properties in the computation. It would be nice if we could also label faces, as these labels can the be used to assign boundary conditions. As currently these need to be coded by hand based on coordinates or normal vectors.

In case of automatic labeling I would see the following groups as useful:
 - [x] Boundary faces (probably split by direction, e.g. top, bottom or Xplus, Xmin, etc.)
 - [x] Faces on the interface between two material regions (e.g. InterfaceSiliconAir for the regions Silicon and Air)
 - [x] Internal faces inside a region (e.g. InternalSilicon), to ensure that each face has a group.

Before doing this we need to check that this can be exported to gmsh. Based on the specification I think that this is possible. However, we would need to use the same route as is requested for elements in #135.

**Comment by stefsmeets** [comment]
Hi @laar, thanks for the suggestion!

Currently, the cells/elements (tetrahedra or triangles) and corresponding points are exported. I can assign labels to either, and this is also supported by `meshio` (via the `cell_data` / `point_data` attributes).

In which way are the faces you mention different from the cells/points? Do you have an example of what this data would look like?

**Comment by Laar** [comment]
> Currently, the cells/elements (tetrahedra or triangles) and corresponding points are exported. I can assign labels to either, and this is also supported by `meshio` (via the `cell_data` / `point_data` attributes).

As far as I see the gmsh format supports assigning regions to cells of arbitrary dimension, as long as a region only contains cells of the same dimension (e.g. only faces, or only elements). So assuming that meshio can import the gmsh files and export them without loss of information, then I think it might support labeling faces as well.

> In which way are the faces you mention different from the cells/points? Do you have an example of what this data would look like?

The data is practically the same as when grouping cells/points but just associated with different parts of the mesh. Which is needed as an element can have faces that are in different groups and points can be the boundary between two face groups. Maybe easier to discuss face to face?

**Comment by stefsmeets** [comment]
Thanks, I understand a bit better now. `nanomesh` should keep track of the contours and save them as a set of cells (somehow separate from the mesh) in the output file.

**Comment by stefsmeets** [comment]
Got a first working version of retrieving the edge information. Gray = outer boundary, red = inner boundary, gray = everything else:

![image](https://user-images.githubusercontent.com/873520/141815411-3a2b32bc-76ba-4485-a710-23f2a490642c.png)

**Comment by Laar** [comment]
That looks like nice progress

**Comment by stefsmeets** [comment]
Hi @laar, this is what I came up with: https://nanomesh.readthedocs.io/en/latest/examples/How%20to%20generate%20a%20triangle%20mesh%20from%20a%202D%20image.html#Field-data

Could you have a look and let me know if that works for you? There will probably be some rough edges still 😅

**Comment by Laar** [comment]
@stefsmeets Looks very nice.

The suggestions of labeling the multiple boundaries came from the following problem:
 - I want to compute the energy flow through the front and back side of the crystal separately (as those correspond to reflection and transmission). Currently this corresponds to the boundary at x=0 and x=L
 - Additionally, not energy should leak to the sides (y=0, y=y1), I would like to verify this energy flow.
 - I'm adding absorbing boundary regions, so that my domain will look like a 5 layer cake: absorber, air, crystal, silicon, absorber instead of the current 3 layer one (air, crystal, silicon). So then I would need to compute the energy flow not at the air boundary, but on the interface between air and the absorber.

For the internal boundaries I could do most of the work by looking at the names of the adjacent zones. But for the external boundaries I don't have any way of properly distinguishing the several parts (left, right, top, bottom).

**Comment by stefsmeets** [comment]
Alright, thanks! Then this issue can be closed. I will keep track of the progress labeling the boundary interfaces separately in a new issue. 🚀
