### ISSUE TITLE
Simple access to the (top level) cell count

### ISSUE THREAD

**Issue by Laar** [hpgem/nanomesh#209]
The computational cost that is associated with using a FEM mesh primarily depends on the number of elements (e.g. triangles in a 2D mesh). Thus during meshing it is useful to print the number of elements, to allow balancing the mesh resolution vs the computational cost. For that reason it would be useful to easily get the number of elements of a mesh. 

Alternatively, it could be useful to be able to print some additional mesh statistics. For example print the number of elements per region.

**Comment by stefsmeets** [comment]
`print(mesh)` will print the number of elements. 
Is there anything else you would like to see?

**Comment by Laar** [comment]
Oops, completely overlooked your reply. `print(mesh)` looks like it contains all the information that I need.
