### ISSUE TITLE
Allow disabling feature markers

### ISSUE THREAD

**Issue by Laar** [hpgem/nanomesh#228]
Plotting a mesh with region markers, seems to force the markers to be visible. This is useful when debugging, but not when plotting for manuscripts. It would be useful to allow disabling the feature markers (just as we can only plot a subsection of the region boundaries).

As example:
![x500-s14-strip1-borderless-segmentation](https://user-images.githubusercontent.com/731831/154048769-4efc4f98-2b3f-474e-86af-f3fe5f20edf2.png)

**Comment by stefsmeets** [comment]
As a work-around, you can do `mesh.region_markers.clear()`.

I will make a PR in which you can specify `show_region_markers=False` 👍

**Comment by Laar** [comment]
> As a work-around, you can do `mesh.region_markers.clear()`.

It seems that the markers in the `Mesher2D` are automatically regenerated. So I can clear them, but they directly reappear.
