### ISSUE TITLE
tetgen errors

### ISSUE THREAD

**Issue by jgostick** [hpgem/nanomesh#290]
Hey Team...firstly thanks for this great library. I have high hopes for it.  

I was playing with generating a mesh of a 3D voxel image [following this example](https://nanomesh.readthedocs.io/en/latest/examples/nanopores_generate_a_3d_tetrahedral_mesh.html)

But I am getting this error: "FileNotFoundError: [WinError 2] The system cannot find the file specified" when I call the ``mmesh = mesher.tetrahedralize(opts='-pAq')``.  I have installed ``pyvista`` and a few other pip packages related to the mesh generation, but I have not compiled and installed the ``tetgen`` code itself.  Is this necessary or should the pyvista package come with the tetgen binaries included?  

Note: I generally avoid any packages that require user compilation because this is not something that most users can or want to do.

**Comment by stefsmeets** [comment]
Hi @jgostick, can you tell me if tetgen is available via the command line? Sometimes you have to set the path in an [environment variable](https://www.computerhope.com/issues/ch000549.htm#windows11).

I agree with you on avoiding packages that require compilation, it can be a bit of a pain especially on Windows. Tetgen is available via conda, but I also host compiled versions of tetgen [here](https://github.com/hpgem/tetgen/releases). For more info, see the [documentation](https://nanomesh.readthedocs.io/en/latest/install.html#tetgen)

**Comment by jgostick** [comment]
Ok, all fixed now.  I had install pyvista and nanomesh, and a few others like mehshio etc, so was surprized that the mesh step didn't work, as I assumed that at least one of these packages had included `tetgen` as a dependency.  Your mention of the `tetgen` conda package did the trick though, once I installed it things are now working. 

Out of curiousity, did I miss some instruction somewhere telling me to do `conda install -c conda-forge tetgen`?  

Thanks!
![index](https://user-images.githubusercontent.com/5092049/202780333-4adcbd47-34ba-4f29-884a-5549c09364d2.png)

**Comment by stefsmeets** [comment]
Glad to hear! There is a python library that pyvista depends on (pytetgen), it works well, but it's quite limited. For Nanomesh we opted to call tetgen from the command line to get access to all its capabilities.

> Out of curiousity, did I miss some instruction somewhere telling me to do `conda install -c conda-forge tetgen`?

You can find it in the documentation here: https://nanomesh.readthedocs.io/en/latest/install.html#tetgen
But maybe I should place it in a more prominent place!
