### ISSUE TITLE
How to detect multiple regions by colors?

### ISSUE THREAD

**Issue by adtzlr** [hpgem/nanomesh#295]
Hi @stefsmeets ,

I'd like to ask if `nanomesh` can detect multiple groups of regions by their colors or grayscale values of a 2d image. Is it possible to create grouped regions for the white, the gray and the black regions of a png-image?

![image2](https://github.com/hpgem/nanomesh/assets/5793153/f43925c0-d7f0-4735-876f-a63187f1dd83)

I've read through the docs and I could extract the black regions with success.

![image](https://github.com/hpgem/nanomesh/assets/5793153/3b809f2e-489f-4d70-bc5c-b07414890eef)

However, I'm interested in the different regions associated to the colors of an image, i.e. I'd like to obtain *feature 1* from gray, *feature 2* from black and *background* from white instead of only *feature* and *background*.

Thanks in advance!

**Comment by stefsmeets** [comment]
Hi @adtzlr I believe the tricky bit here is that the gray and black are directly connected. Nanomesh doesn't really know how to set that up correctly for meshing.

One thing you could try to manually set the regions (i.e. assign different labels to your contour) before meshing (https://nanomesh.readthedocs.io/en/latest/examples/examples_generate_a_2d_triangular_mesh.html#Region-markers).

**Comment by adtzlr** [comment]
Hi and thanks for your hints! Unfortunately, this is still not exactly what I'm looking for.

<details><summary>code</summary>

```python
import matplotlib.pyplot as plt
import numpy as np

data = plt.imread("drawing.png")
plt.imshow(data)

from nanomesh import Image, Mesher2D
import nanomesh

plane = Image(data)
mesher = Mesher2D(plane)
mesher.generate_contour(max_edge_dist=10, level=1, group_regions=False)

colors = []
for i, region_marker in enumerate(mesher.contour.region_markers):
    point = np.array(region_marker.point).astype(int)
    colors.append(data[point[0], point[1]])
    
colors = np.unique(colors)
names = np.array(["material A", "material B", "material C"])

for i, region_marker in enumerate(mesher.contour.region_markers):
    point = np.array(region_marker.point).astype(int)
    color = data[point[0], point[1]]
    region_marker.label = np.argwhere([color == c for c in colors])[0][0]
    region_marker.name = names[[color == c for c in colors]][0]

mesher.plot_contour()

mesh = mesher.triangulate(opts='q30a400')
triangle_mesh = mesh.get('triangle')

triangle_mesh.plot()
```
</details>

From this image

![image](https://github.com/hpgem/nanomesh/assets/5793153/c00ac709-abc6-4ce4-8eea-37cd6c9a4f0d)


I managed to get

![image](https://github.com/hpgem/nanomesh/assets/5793153/9fef9902-cab4-4846-97e2-666a488e30d1)

and 

![image](https://github.com/hpgem/nanomesh/assets/5793153/c533a478-6603-478a-bcb1-4119bb475a5b)

If I could only manage to separate the dark edges into a separate region...

Anyway, thanks a lot!

**Comment by stefsmeets** [comment]
I see what you mean, nested regions are unfortunately not possible with Nanomesh at this moment. Maybe you can do some trickery to work around it.

**Comment by stefsmeets** [comment]
You could try invoke triangle directly: https://rufat.be/triangle/examples.html
