### ISSUE TITLE
How can i set subdomains to apply boundary conditions?

### ISSUE THREAD

**Issue by MFV-PS** [hpgem/nanomesh#296]
Hi, I'm working with Stokes flow in porous medium. I'm using irregular porous medium so i tried to figure out how to tag properly the fields generated. The tag 1 correspond to porous space and 2 to inner solids. 
![image](https://github.com/hpgem/nanomesh/assets/167724416/4d4d3263-8f54-40fa-8872-307d7e954206)
however, when i write the .msh file there's a warning "Warning: Appending zeros to replace the missing physical tag data.
Warning: Appending zeros to replace the missing geometrical tag data." I supposed this data is important to differentiate the solids (where i tried to apply Non-Slip condition).  
Thanks in advance.

**Comment by stefsmeets** [comment]
Hi @MFV-PS , the warning is generated by meshio when writing to certain formats. gmsh requires the tag to be set, and if it is empty, it will simply put zeros to have something. 

If you use the `to_meshio` method, you can work with the meshio mesh directly to tweak the tags ([see here for more info](https://nanomesh.readthedocs.io/en/latest/examples/examples_generate_a_2d_triangular_mesh.html#Interoperability)).

Hope this helps.

**Comment by MFV-PS** [comment]
Hi @stefsmeets, I have this doubt, 
When I generated the contour of some irregular shapes two or more straight lines appear between the contours, how can i solve this issue? 
![image](https://github.com/hpgem/nanomesh/assets/167724416/7c797af1-1398-4b61-829e-8a609679ca67)

**Comment by stefsmeets** [comment]
It's likely a bug in the visualizer, it does not handle segments that span from one side to the other very well. The line mesh is a closed loop that goes from A->B->C->D->A, so it will draw a line from one side to the other. If it is for visualization, you may want to drop this segment from the mesh.

**Comment by stefsmeets** [comment]
I'm going to close this issue, but feel free to re-open if you have any further questions!
