### ISSUE TITLE
Meshing 3D volume from instance segmentation

### ISSUE THREAD

**Issue by CheLamVien** [hpgem/nanomesh#298]
Dear all, 

Thank you for the nice Python package.

I have a 3D volume of instance cell segmentation. 
![image](https://github.com/user-attachments/assets/adebff12-3a60-444e-9b0f-2557a742895b)
I have some questions: 
1. It seems like the algorithm only works with binary images. I got the error when executing `tetras = meshes.tetrahedralize(opts='-pAq -a10') ` 
`ReadError: File /tmp/tmp2veg_rlo/nanomesh.1.ele not found.`
2. If I convert the image to binary. The interfaces between the cells will disappear, so the cells will be merged into one, which I don't want to 

Any suggestions and recommendations are highly appreciated. 

Best regards, 
Vien Che

**Comment by stefsmeets** [comment]
Hi @CheLamVien , thanks for reaching out!

I think the issue with your input is that some of the regions are connected, e.g. the clusters with 2 or 3 blobs. I'm not sure that is something that tetgen or triangle (the underlying libraries that nanomesh uses) support.

Somehow tetgen does not produce the expected data, resulting in that error message.

Nanomesh *can* deal with labeled images, see [this link](https://nanomesh.readthedocs.io/en/latest/examples/nanopores_generate_a_3d_tetrahedral_mesh.html#Using-region-markers) for an example.
