### ISSUE TITLE
Pad mesh with custom labels

### ISSUE THREAD

**Issue by Laar** [hpgem/nanomesh#92]
It would be useful to add 1 or more buffer layers around the crystal. This would be used to

 - Let the waves propagate from the crystal before they hit the boundary.
 - As layer where the outgoing wave is absorbed.

The regions themselves are just one material and should have a straight side/interface.

**Comment by stefsmeets** [comment]
Extend the mesh on arbitrary sides with a user-defined pad width and label. Not necessarily pad the entire mesh on all sides.
