### ISSUE TITLE
ROI cutting through the pores

### ISSUE THREAD

**Issue by Laar** [hpgem/nanomesh#93]
Related to #87

I would like to select a ROI that cuts through the centre of the pores. This would be along the line where, if the pores would be round, be mirror symmetric. The reality is of course not symmetric, but a good approximation of the position would be required. This probably requires a non-rectangular cut.

**Comment by stefsmeets** [comment]
Arbitrarily shaped meshes, define ROI from image, and remove contours/triangles from final mesh.
